"""empty message

Revision ID: b674d245312c
Revises: 339a4cdb7cf9
Create Date: 2026-02-14 11:06:43.916029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b674d245312c'
down_revision: Union[str, Sequence[str], None] = '339a4cdb7cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_transactions_date_pay', 'transactions', ['date_pay'], unique=False)
    op.create_index('idx_transactions_status_type_date_user', 'transactions', ['status', 'type', 'date_pay', 'user_id'], unique=False)
    op.create_index('idx_transactions_sum_pay', 'transactions', ['sum_pay'], unique=False)
    op.create_index('idx_transactions_user_id', 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_user_id', table_name='transactions')
    op.drop_index('idx_transactions_sum_pay', table_name='transactions')
    op.drop_index('idx_transactions_status_type_date_user', table_name='transactions')
    op.drop_index('idx_transactions_date_pay', table_name='transactions')
    # ### end Alembic commands ###
